import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[var(--background)]">
      <div className="max-w-2xl mx-auto px-6 py-16">
        <div className="mb-10">
          <Link href="/" className="inline-flex items-center gap-2 mb-8">
            <img src="/logo.png" alt="DrillMe" className="w-8 h-8 rounded object-contain" />
            <span className="text-foreground font-semibold">DrillMe</span>
          </Link>
          <h1 className="text-3xl font-bold text-foreground mb-2">Terms of Service</h1>
          <p className="text-slate-400 text-sm">Last updated: May 2026</p>
        </div>

        <div className="prose prose-slate max-w-none space-y-8 text-slate-300 text-sm leading-relaxed">
          <section>
            <h2 className="text-foreground font-semibold text-base mb-3">1. Acceptance of Terms</h2>
            <p>By accessing or using DrillMe (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the Service.</p>
          </section>

          <section>
            <h2 className="text-foreground font-semibold text-base mb-3">2. Description of Service</h2>
            <p>DrillMe is an AI-powered interview preparation platform that provides mock interview sessions, performance feedback, and practice tools. The Service uses third-party AI models to generate questions and evaluate responses.</p>
          </section>

          <section>
            <h2 className="text-foreground font-semibold text-base mb-3">3. User Accounts</h2>
            <p>You must create an account to use the Service. You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You must be at least 16 years old to use the Service.</p>
          </section>

          <section>
            <h2 className="text-foreground font-semibold text-base mb-3">4. Subscriptions and Billing</h2>
            <p>DrillMe offers a free tier and a paid Pro subscription. Paid subscriptions are billed monthly. You may cancel at any time; access continues until the end of the current billing period. All payments are processed securely by Stripe. We do not store your payment card details.</p>
          </section>

          <section>
            <h2 className="text-foreground font-semibold text-base mb-3">5. Acceptable Use</h2>
            <p>You agree not to: (a) use the Service for any unlawful purpose; (b) attempt to reverse-engineer or extract our AI models or prompts; (c) share account credentials with others; (d) use automated tools to abuse the Service; or (e) upload any content that is harmful, deceptive, or violates third-party rights.</p>
          </section>

          <section>
            <h2 className="text-foreground font-semibold text-base mb-3">6. AI-Generated Content</h2>
            <p>Interview questions, feedback, and evaluations are generated by AI and are for practice purposes only. DrillMe makes no guarantees about the accuracy, completeness, or fitness of AI-generated content for any specific hiring process. AI feedback is not a substitute for professional career coaching.</p>
          </section>

          <section>
            <h2 className="text-foreground font-semibold text-base mb-3">7. Intellectual Property</h2>
            <p>DrillMe and its original content, features, and functionality are owned by DrillMe and protected by applicable intellectual property laws. Your interview transcripts and responses remain your property.</p>
          </section>

          <section>
            <h2 className="text-foreground font-semibold text-base mb-3">8. Disclaimer of Warranties</h2>
            <p>The Service is provided &quot;as is&quot; without warranties of any kind. We do not guarantee that the Service will be uninterrupted, error-free, or that practice sessions will result in job offers.</p>
          </section>

          <section>
            <h2 className="text-foreground font-semibold text-base mb-3">9. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, DrillMe shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service.</p>
          </section>

          <section>
            <h2 className="text-foreground font-semibold text-base mb-3">10. Changes to Terms</h2>
            <p>We may update these terms from time to time. Continued use of the Service after changes constitutes acceptance of the new terms.</p>
          </section>

          <section>
            <h2 className="text-foreground font-semibold text-base mb-3">11. Contact</h2>
            <p>Questions about these terms? Contact us at <a href="mailto:drillme26@gmail.com" className="text-blue-400 hover:text-blue-300">drillme26@gmail.com</a></p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-[var(--card-border)] flex gap-6 text-sm">
          <Link href="/privacy" className="text-blue-400 hover:text-blue-300">Privacy Policy</Link>
          <Link href="/" className="text-slate-400 hover:text-foreground">Back to home</Link>
        </div>
      </div>
    </div>
  );
}
